# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '4JANA-Project-Mona' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 4JANA-Project-Mona
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
