# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jana' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jana


  pod 'SwifterSwift', '5.0.0'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'YPImagePicker', '4.2.0'
  pod 'SVProgressHUD', '2.2.5'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'CodableFirebase', '0.2.0'
  pod 'ActionSheetPicker-3.0'
  pod 'SDWebImage', '~> 4.0'
  pod "TTGSnackbar", '1.10.5'
  
end
